In [28]:
import pandas as pd
from pathlib import Path
import numpy as np

In [49]:
pre_filter_path = Path("/project/imoskowitz/yubin/1-sc_practice/Differential_Gene_Analysis/DataFrames/Pre-pseudobulk-filter")
post_filter_path = Path("/project/imoskowitz/yubin/1-sc_practice/Differential_Gene_Analysis/DataFrames/Post-pseudobulk-filter")

In [50]:
pre_filter_path = sorted(pre_filter_path.iterdir())
post_filter_path = sorted(post_filter_path.iterdir())

In [51]:
pre_filters = [] # list of pre filter DEG ranging from genes present in 0-5 cells filter
for file_path in pre_filter_path:
    if file_path.is_file():  
        pre_filters.append(pd.read_csv(file_path))

post_filters = [] # list of post filter DEG ranging from genes present in 0-5 cells filter
for file_path in post_filter_path:
    if file_path.is_file():  
        post_filters.append(pd.read_csv(file_path))

In [52]:
for filter in pre_filters:
    display(filter.describe())

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
count,33696.000000,26519.000000,26519.000000,26519.000000,2.651800e+04,1.688800e+04
mean,339.249365,-0.029723,1.079296,-0.014722,4.389476e-01,4.275271e-01
std,1371.685716,0.880375,1.346105,1.943030,3.378606e-01,3.400513e-01
min,0.000000,-5.458883,0.068071,-18.348954,4.748977e-110,8.020072e-106
25%,0.190587,-0.376919,0.152204,-0.769246,8.771830e-02,8.018277e-02
50%,6.821324,-0.020971,0.391658,-0.047708,4.351838e-01,4.046555e-01
75%,191.523384,0.325470,1.478522,0.795716,7.418937e-01,7.490980e-01
max,150582.075396,10.464265,4.427580,22.288766,9.999216e-01,9.999216e-01

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
count,26519.000000,26519.000000,26519.000000,26519.000000,2.651800e+04,1.674900e+04
mean,431.062507,-0.029723,1.079296,-0.014722,4.389476e-01,4.251840e-01
std,1533.352534,0.880375,1.346105,1.943030,3.378606e-01,3.402319e-01
min,0.106224,-5.458883,0.068071,-18.348954,4.748977e-110,7.954061e-106
25%,1.945687,-0.376919,0.152204,-0.769246,8.771830e-02,7.829096e-02
50%,31.133675,-0.020971,0.391658,-0.047708,4.351838e-01,3.985199e-01
75%,321.159967,0.325470,1.478522,0.795716,7.418937e-01,7.467894e-01
max,150582.075396,10.464265,4.427580,22.288766,9.999216e-01,9.999216e-01

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
count,24709.000000,24709.000000,24709.000000,24709.000000,2.470800e+04,1.656400e+04
mean,462.627204,-0.062242,0.839287,-0.022283,4.096397e-01,4.230766e-01
std,1583.921785,0.865882,1.038886,2.007958,3.287283e-01,3.400351e-01
min,0.212449,-5.458914,0.068080,-18.382475,1.192219e-110,1.974792e-106
25%,3.327525,-0.425796,0.145933,-0.860429,7.019419e-02,7.604316e-02
50%,46.496562,-0.010309,0.331863,-0.020417,3.852141e-01,3.954887e-01
75%,365.046155,0.310213,1.126533,0.876993,7.123972e-01,7.437695e-01
max,150582.075396,10.464266,4.346008,22.350566,9.999413e-01,9.999413e-01

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
count,23640.000000,23640.000000,23640.000000,23640.000000,2.363900e+04,1.630600e+04
mean,483.532678,-0.072515,0.702398,-0.026352,3.941587e-01,4.192077e-01
std,1616.217512,0.838144,0.826647,2.046499,3.257377e-01,3.396676e-01
min,0.318673,-5.458932,0.069299,-18.442526,4.143305e-111,6.756073e-107
25%,4.735855,-0.404822,0.142453,-0.910298,6.160079e-02,7.446915e-02
50%,57.977805,-0.014317,0.301252,-0.036820,3.581012e-01,3.873727e-01
75%,396.581494,0.287342,0.959780,0.931708,6.766785e-01,7.396418e-01
max,150582.075396,10.464299,4.301682,22.397711,9.999596e-01,9.999596e-01

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
count,22875.000000,22875.000000,22875.000000,22875.000000,2.287400e+04,1.622100e+04
mean,499.687329,-0.074308,0.618160,-0.028392,3.829707e-01,4.187620e-01
std,1640.565571,0.808670,0.695469,2.077268,3.231642e-01,3.397503e-01
min,0.424897,-5.458931,0.070049,-18.473597,3.139949e-111,5.093312e-107
25%,6.009248,-0.395579,0.139719,-0.946522,5.561358e-02,7.397033e-02
50%,66.829561,-0.006830,0.281170,-0.020441,3.394267e-01,3.859596e-01
75%,418.736040,0.284983,0.846271,0.966755,6.684294e-01,7.388169e-01
max,150582.075396,10.464320,3.952118,22.410063,9.999819e-01,9.999819e-01

In [55]:
for filter in post_filters:
    display(filter.describe())

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
count,33696.000000,26519.000000,26519.000000,26519.000000,2.651800e+04,1.688800e+04
mean,339.249365,-0.029723,1.079296,-0.014722,4.389476e-01,4.275271e-01
std,1371.685716,0.880375,1.346105,1.943030,3.378606e-01,3.400513e-01
min,0.000000,-5.458883,0.068071,-18.348954,4.748977e-110,8.020072e-106
25%,0.190587,-0.376919,0.152204,-0.769246,8.771830e-02,8.018277e-02
50%,6.821324,-0.020971,0.391658,-0.047708,4.351838e-01,4.046555e-01
75%,191.523384,0.325470,1.478522,0.795716,7.418937e-01,7.490980e-01
max,150582.075396,10.464265,4.427580,22.288766,9.999216e-01,9.999216e-01

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
count,26519.000000,26519.000000,26519.000000,26519.000000,2.651800e+04,1.674900e+04
mean,431.062507,-0.029723,1.079296,-0.014722,4.389476e-01,4.251840e-01
std,1533.352534,0.880375,1.346105,1.943030,3.378606e-01,3.402319e-01
min,0.106224,-5.458883,0.068071,-18.348954,4.748977e-110,7.954061e-106
25%,1.945687,-0.376919,0.152204,-0.769246,8.771830e-02,7.829096e-02
50%,31.133675,-0.020971,0.391658,-0.047708,4.351838e-01,3.985199e-01
75%,321.159967,0.325470,1.478522,0.795716,7.418937e-01,7.467894e-01
max,150582.075396,10.464265,4.427580,22.288766,9.999216e-01,9.999216e-01

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
count,24456.000000,24456.000000,24456.000000,24456.000000,2.445500e+04,1.639400e+04
mean,467.409668,-0.059816,0.800831,-0.022850,4.062533e-01,4.193969e-01
std,1591.392258,0.851434,0.979475,2.016117,3.286804e-01,3.396093e-01
min,0.239033,-5.458899,0.069566,-18.412059,1.910542e-110,3.132142e-106
25%,3.616787,-0.410122,0.144897,-0.873357,6.730289e-02,7.436074e-02
50%,49.009137,-0.007236,0.322677,-0.012824,3.778037e-01,3.864046e-01
75%,372.786692,0.310128,1.082097,0.892044,7.067527e-01,7.397220e-01
max,150582.075396,10.464306,4.212505,22.329500,9.999987e-01,9.999987e-01

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
count,22989.000000,22989.000000,22989.000000,22989.000000,2.298800e+04,1.674800e+04
mean,497.209291,-0.061367,0.621313,-0.026174,3.854710e-01,4.272331e-01
std,1636.869083,0.791398,0.697914,2.069938,3.251466e-01,3.399754e-01
min,0.403257,-5.458872,0.072561,-18.442738,1.118693e-109,1.873586e-105
25%,5.808401,-0.382104,0.140322,-0.945823,5.621061e-02,8.118482e-02
50%,65.790259,-0.007283,0.281287,-0.022329,3.403518e-01,3.999215e-01
75%,415.790307,0.286559,0.851606,0.963197,6.714879e-01,7.490587e-01
max,150582.075396,10.464398,3.741733,22.250369,9.999835e-01,9.999835e-01

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
count,21810.000000,21810.000000,21810.000000,21810.000000,2.180900e+04,1.631200e+04
mean,524.041347,-0.056598,0.514367,-0.025720,3.716791e-01,4.180953e-01
std,1676.349367,0.709097,0.538336,2.119107,3.236013e-01,3.391420e-01
min,0.593844,-5.458851,0.072895,-18.401136,5.855598e-109,9.551652e-105
25%,8.401980,-0.361859,0.136398,-0.993813,4.785197e-02,7.512867e-02
50%,81.581061,-0.000414,0.255454,-0.001833,3.138395e-01,3.834889e-01
75%,455.138060,0.278437,0.710717,1.024561,6.558697e-01,7.365350e-01
max,150582.075396,10.464412,2.633146,22.176003,9.999880e-01,9.999880e-01

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
count,20516.000000,20516.000000,20516.000000,20516.000000,2.051500e+04,1.653700e+04
mean,557.007355,-0.046642,0.426986,-0.020007,3.590366e-01,4.232704e-01
std,1723.102306,0.631511,0.415297,2.175276,3.225684e-01,3.394786e-01
min,0.805426,-3.800364,0.072724,-18.436817,1.615759e-109,2.671981e-105
25%,12.694473,-0.335521,0.132654,-1.035252,3.949803e-02,7.879152e-02
50%,102.956337,0.002547,0.232364,0.008789,2.879612e-01,3.927862e-01
75%,502.560519,0.267711,0.588185,1.091389,6.373275e-01,7.419526e-01
max,150582.075396,10.464403,2.633146,22.233873,9.999849e-01,9.999849e-01

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
count,19004.000000,19004.000000,19004.000000,19004.000000,1.900300e+04,1.605500e+04
mean,601.100695,-0.038500,0.350614,-0.009765,3.444087e-01,4.163584e-01
std,1782.955580,0.572621,0.312886,2.245813,3.208947e-01,3.392515e-01
min,1.027172,-3.737366,0.071450,-18.495958,6.288539e-111,1.009625e-106
25%,20.781946,-0.305081,0.128531,-1.084844,3.102390e-02,7.285414e-02
50%,132.505420,0.007924,0.210537,0.032601,2.598019e-01,3.814178e-01
75%,566.758380,0.259023,0.475287,1.167723,6.176694e-01,7.353555e-01
max,150582.075396,10.464361,1.807371,22.379111,9.999970e-01,9.999970e-01

In [ ]:
for filter in pre_filters:
    # Display basic info about the dataframe
    print("Dataframe Info:")
    display(filter.info())

    # Display the first few rows to understand the structure
    print("\nFirst 5 rows:")
    display(filter.head())

    # Generate summary statistics for numerical columns
    print("\nSummary Statistics (numerical columns):")
    display(filter.describe())

In [56]:
[len(filter) for filter in pre_filters]

[33696, 26519, 24709, 23640, 22875]

In [57]:
[len(filter) for filter in post_filters]

[33696, 26519, 24456, 22989, 21810, 20516, 19004]